user:
  database:
    host: "localhost"
    user: "postgres"
    dbname: "user"
    password: "admin"
    port: "5432"
  service:
    url: "localhost"
    port: "8081"

decoder:
  database:
    host: "localhost"
    user: "postgres"
    password: "admin"
    port: "5432"
  service:
    url: "localhost"
    port: "8082"